// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ChatRoom
    {
        public ChatRoom()
        {
            Messagesses = new HashSet<Messagess>();
        }

        public int ChatRoomId { get; set; }
        public int? UserId { get; set; }
        public DateTime ChatRoomTime { get; set; }
        public int? PostId { get; set; }

        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Messagess> Messagesses { get; set; }
    }
}