// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ClassCourse
    {
        public ClassCourse()
        {
            ClassChapters = new HashSet<ClassChapter>();
            ClassContentImages = new HashSet<ClassContentImage>();
            ClassQas = new HashSet<ClassQa>();
            ClassScores = new HashSet<ClassScore>();
            ClassTexts = new HashSet<ClassText>();
            ShoppingAddToCarts = new HashSet<ShoppingAddToCart>();
            ShoppingOrderDetails = new HashSet<ShoppingOrderDetail>();
        }

        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int? UserId { get; set; }
        public int? CourseCategoryId { get; set; }
        public string CourseIntro { get; set; }
        public decimal? CoursePrice { get; set; }
        public string CourseImageUrl { get; set; }
        public string CourseIntroVideo { get; set; }
        public int? CourseDuration { get; set; }
        public int? CourseChapter { get; set; }
        public string CourseContent { get; set; }

        public virtual ClassCategory CourseCategory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ClassChapter> ClassChapters { get; set; }
        public virtual ICollection<ClassContentImage> ClassContentImages { get; set; }
        public virtual ICollection<ClassQa> ClassQas { get; set; }
        public virtual ICollection<ClassScore> ClassScores { get; set; }
        public virtual ICollection<ClassText> ClassTexts { get; set; }
        public virtual ICollection<ShoppingAddToCart> ShoppingAddToCarts { get; set; }
        public virtual ICollection<ShoppingOrderDetail> ShoppingOrderDetails { get; set; }
    }
}