// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ClassQa
    {
        public int CourseQaid { get; set; }
        public int? CourseId { get; set; }
        public string CourseQamessage { get; set; }
        public DateTime? Qatime { get; set; }
        public int? UserId { get; set; }

        public virtual ClassCourse Course { get; set; }
        public virtual User User { get; set; }
    }
}