// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class Messagess
    {
        public int MessageId { get; set; }
        public int? ChatRoomId { get; set; }
        public int? UserId { get; set; }
        public string MessageContent { get; set; }
        public DateTime MessageTime { get; set; }

        public virtual ChatRoom ChatRoom { get; set; }
        public virtual User User { get; set; }
    }
}