// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class Post
    {
        public Post()
        {
            Books = new HashSet<Book>();
            ChatRooms = new HashSet<ChatRoom>();
            Comments = new HashSet<Comment>();
            Thumbs = new HashSet<Thumb>();
        }

        public int PostId { get; set; }
        public int? UserId { get; set; }
        public string PostCategory { get; set; }
        public string PostTitle { get; set; }
        public DateTime PostPublishTime { get; set; }
        public string PostContent { get; set; }
        public string PostTag1 { get; set; }
        public string PostTag2 { get; set; }
        public string PostTag3 { get; set; }
        public string HiddenPost { get; set; }
        public string PostrImgUrl { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<ChatRoom> ChatRooms { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Thumb> Thumbs { get; set; }
    }
}