// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ShoppingOrderDetail
    {
        public int OrderDetailId { get; set; }
        public int? OrderId { get; set; }
        public int? CourseId { get; set; }
        public int? Price { get; set; }

        public virtual ClassCourse Course { get; set; }
        public virtual ShoppingOrder Order { get; set; }
    }
}