// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class Thumb
    {
        public int ThumbId { get; set; }
        public int? UserId { get; set; }
        public int? PostId { get; set; }
        public DateTime ThumbTime { get; set; }

        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}