// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class UserTeacher
    {
        public int TeacherId { get; set; }
        public int UserId { get; set; }
        public string UserIntro1 { get; set; }
        public string UserIntro2 { get; set; }
        public string UserBgimage { get; set; }

        public virtual User User { get; set; }
    }
}