// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewBuiedTotalPrice
    {
        public int? UserId { get; set; }
        public int? TotalPrice { get; set; }
    }
}