// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewBuiedCoursesName
    {
        public int ShoppingCartId { get; set; }
        public string UserName { get; set; }
        public int? UserId { get; set; }
        public string UserEmail { get; set; }
        public int? CourseId { get; set; }
        public string CourseName { get; set; }
        public decimal? CoursePrice { get; set; }
    }
}