// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewClassStartVideo
    {
        public string CourseName { get; set; }
        public int CourseId { get; set; }
        public int? CourseCategoryId { get; set; }
        public string CourseIntro { get; set; }
        public string CourseImageUrl { get; set; }
        public string CourseIntroVideo { get; set; }
        public int? CourseDuration { get; set; }
        public string CourseContent { get; set; }
        public int ChapterId { get; set; }
        public string CourseVideo { get; set; }
        public string ChapterTitle { get; set; }
    }
}