// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewUserCourse
    {
        public int UserId { get; set; }
        public string UserCourseName { get; set; }
        public int? CourseId { get; set; }
        public string CourseName { get; set; }
        public string UserCourseImageUrl { get; set; }
        public string CourseIntro { get; set; }
        public int? CourseDuration { get; set; }
        public decimal? CoursePrice { get; set; }
        public string CourseCategoryName { get; set; }
        public int? CourseCategoryId { get; set; }
    }
}