// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewClassPageTop
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int? CourseCategoryId { get; set; }
        public string CourseCategoryName { get; set; }
        public int? UserId { get; set; }
        public string CourseIntro { get; set; }
        public string UserName { get; set; }
        public string CourseIntroVideo { get; set; }
    }
}