// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewOrderDetailsInIndex
    {
        public int OrderDetailId { get; set; }
        public int? OrderId { get; set; }
        public int? CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseImageUrl { get; set; }
        public int? CourseDuration { get; set; }
        public int? UserId { get; set; }
        public string UserName { get; set; }
        public string UserTeacherName { get; set; }
    }
}