// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewClassQabefore
    {
        public int CourseQaid { get; set; }
        public int? CourseId { get; set; }
        public int? QauserId { get; set; }
        public string Qauser { get; set; }
        public string UserImageUrl { get; set; }
        public string CourseQamessage { get; set; }
        public DateTime? Qatime { get; set; }
    }
}