// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewChatRoom
    {
        public int ChatRoomId { get; set; }
        public int? UserId { get; set; }
        public string UserName { get; set; }
        public string UserImageUrl { get; set; }
        public DateTime ChatRoomTime { get; set; }
        public int? PostId { get; set; }
        public string PostTitle { get; set; }
        public string PosterName { get; set; }
        public int? PosterId { get; set; }
        public string Posterimg { get; set; }
    }
}