// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewPostThumbCount
    {
        public int PostId { get; set; }
        public int? PostThumbCount { get; set; }
    }
}