// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewUserTeacher
    {
        public int UserId { get; set; }
        public string UserTeacherName { get; set; }
        public string TeacherImage { get; set; }
        public string UserIntro1 { get; set; }
        public string UserIntro2 { get; set; }
    }
}