// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewTeacherCourse
    {
        public int UserId { get; set; }
        public string UserTeacherName { get; set; }
        public string TeacherImage { get; set; }
        public string UserIntro1 { get; set; }
        public string UserIntro2 { get; set; }
        public string CourseImageUrl { get; set; }
        public int? CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseIntro { get; set; }
        public decimal? CoursePrice { get; set; }
        public int? CourseDuration { get; set; }
    }
}