// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewPostComment
    {
        public int? PostId { get; set; }
        public int CommentId { get; set; }
        public int? CommentUserId { get; set; }
        public string CommentUser { get; set; }
        public string UserImageUrl { get; set; }
        public string CommentContent { get; set; }
        public DateTime? CommentTime { get; set; }
    }
}