// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewChatRoomMessage
    {
        public int MessageId { get; set; }
        public int? ChatRoomId { get; set; }
        public int? UserId { get; set; }
        public string UserName { get; set; }
        public string UserImageUrl { get; set; }
        public string MessageContent { get; set; }
        public DateTime MessageTime { get; set; }
        public int? ChatRoomsPostId { get; set; }
        public string PostTitle { get; set; }
        public int? PosterId { get; set; }
    }
}