// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MVC.Models
{
    public partial class ViewClassText
    {
        public int CourseTextId { get; set; }
        public int? CourseId { get; set; }
        public int? TextUserId { get; set; }
        public string TextUser { get; set; }
        public string UserImageUrl { get; set; }
        public string CourseText { get; set; }
        public DateTime? TextTime { get; set; }
    }
}